version: '3.8'

services:
  app:
    build: .
    ports:
      - '3030:3030'
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  mongo-data:
